[package]
name = "syslogrs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mio = { version = "0.8.2", features = ["net", "os-poll"] }
socket2 = { version = "0.3.9", features = ["reuseport"] }