[config]
# pipe logs to stdout (default: true)
display_stdout = true
# store logs (default: false)
store_logs = false
# compress logs on rotation (default: false)
compress = false
# interval in seconds to rotate logs (default: 86400)
log_rotate_interval = 86400
# directory to store logs (default: './')
log_dir = "./"
# listening port (default: 514)
port = 514
